name: LEAN_CNN_pruning
channels:
  - aahendriksen 
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - pytest
  - pytorch==1.4.0
  - msd_pytorch>=0.8.0
  - networkx>=2.4
  - numba>=0.49.1
  - torchvision>=0.5.0
